CREATE SCHEMA bbcbank;
USE bbcbank;

CREATE TABLE bbcbank.CUSTOMER (
   ID                 INT NOT NULL AUTO_INCREMENT,
   CUSTOMER_NUMBER    VARCHAR(10) NOT NULL,	
   TITLE              VARCHAR(10) NOT NULL, 
   FIRST_NAME         VARCHAR(30) NOT NULL,
   LAST_NAME          VARCHAR(30) NOT NULL, 
   STREET             VARCHAR(30) NOT NULL,
   CITY               VARCHAR(30) NOT NULL,
   ZIPCODE            SMALLINT NOT NULL,
   PRIMARY KEY (ID)
);

ALTER TABLE CUSTOMER ADD UNIQUE INDEX (CUSTOMER_NUMBER); 
 
CREATE TABLE bbcbank.ACCOUNT (
   ID                 INT NOT NULL AUTO_INCREMENT,
   IBAN               VARCHAR(30) NOT NULL,
   BALANCE            DECIMAL(9,2) NOT NULL,
   OVERDRAFT          DECIMAL(7,2) NOT NULL,
   CUSTOMER_ID        INT NOT NULL,
   PRIMARY KEY (ID)
);

ALTER TABLE bbcbank.ACCOUNT
   ADD CONSTRAINT Customer FOREIGN KEY (CUSTOMER_ID)
   REFERENCES bbcbank.CUSTOMER (ID) ON DELETE RESTRICT;

ALTER TABLE ACCOUNT ADD UNIQUE INDEX (IBAN);

CREATE TABLE bbcbank.TRANSACTION_RECORD (
   ID                 INT NOT NULL AUTO_INCREMENT,
   TYPE               CHAR(1) NOT NULL,
   TEXT               VARCHAR(30) NOT NULL,
   AMOUNT             DECIMAL(9,2) NOT NULL,
   TRANSACTION_TIME   TIMESTAMP NOT NULL,
   ACCOUNT_ID         INT NOT NULL,
   PRIMARY KEY (ID)
);

ALTER TABLE bbcbank.TRANSACTION_RECORD
   ADD CONSTRAINT Transactionrecord FOREIGN KEY (ACCOUNT_ID)
   REFERENCES bbcbank.ACCOUNT (ID) ON DELETE RESTRICT;

INSERT INTO CUSTOMER (CUSTOMER_NUMBER, TITLE, FIRST_NAME, LAST_NAME, STREET, CITY, ZIPCODE) VALUES
('585-123456', 'Herr', 'Peter', 'Müller', 'Bahnhofstrasse 1', 'Zürich', 8000);

INSERT INTO ACCOUNT (IBAN, BALANCE, OVERDRAFT, CUSTOMER_ID) VALUES
('CH320058558512345601T', 900.00, 1000, 1),
('CH320058558512345601M', 0, 0, 1);

INSERT INTO TRANSACTION_RECORD (TYPE, TEXT, AMOUNT, TRANSACTION_TIME, ACCOUNT_ID) VALUES
('C', 'Einzahlung', 1000.00, CURRENT_TIMESTAMP, 1),
('D', 'Auszahlung', 100.00, CURRENT_TIMESTAMP, 1);


SELECT * FROM CUSTOMER;
SELECT * FROM ACCOUNT;
SELECT * FROM TRANSACTION_RECORD;

COMMIT;
